version: "3"
services: 
   event-app:
     container_name: event-webapp
     image: event-app:latest
     ports:
       - 3001:3000
     networks:
       - eventapp-network
     volume: 
        - 
networks:
    eventapp-network:
         eventapp-networks
volumes:
   app-data:
      app-data
   
   
     
