version: "3"
services: 
   event-app:
     build:
      context: .
     container_name: eventapp-frontend
     image: event-app:latest
     ports:
       - 3002:3000
     networks:
       - eventapp-network
     environment:
      REACT_APP_BASE_URL: "http://localhost:3001" 
      REACT_APP_WS_URL: "ws://event-localhost:3001/ws"
        
networks:
   eventapp-network:
     external: true



   
   
     
